// Burger Builder
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// Checkout / Orders
export const ORDER_PURCHASE_START = 'ORDER_PURCHASE_START';
export const ORDER_PURCHASE_SUCCESS = 'ORDER_PURCHASE_SUCCESS';
export const ORDER_PURCHASE_FAIL = 'ORDER_PURCHASE_FAIL';
export const ORDER_PURCHASE_INIT = 'ORDER_PURCHASE_INIT';

// View Orders
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';